### ISSUE TITLE
handleExpect

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#186]
I resumed to hack the request parser of Warp. I have a question.

`Request.handleExpect` removes the Expect header from a list. Why should it be removed?

**Comment by reiddraper** [comment]
> The expect header for 100-continue values is an artifact of the HTTP layer itself, and would have no bearing on the web application. There's no theoretical downside to passing it on to the application, but the application can't do anything meaningful with that information.

I think the web application _can_ do something meaningful with this. From [RFC 2616](https://www.ietf.org/rfc/rfc2616.txt), section 8.2.3:

> In some cases, it might either be inappropriate or highly inefficient for the client to send the body if the server will reject the message without looking at the body.

As a concrete example, imagine writing an API or web application that processes large POST or PUT requests. Each request includes an authentication header (cookie, or otherwise). Based on the URL and header alone, the server may determine that the request is not authorized, and return HTTP 403, before the client has sent a multi gigabyte or megabyte request body.

Another example would be the web application responding with HTTP 413, having just looked at the Content-Length header.

How this fits in with Wai/Warp, I'm not entirely sure. One idea might be to introduce a Warp configuration option which would _not_ automatically respond with `100-continue`. _IFF_ the application called `Wai. requestBody` would Warp send `100-continue`, and begin reading. Since this would be an opt-in configuration option, existing users would not be affected.

Thoughts?

**Comment by kazu-yamamoto** [comment]
I also feel the current behavior is hard-coding, too. I would like to let applications to decide their behavior.

**Comment by reiddraper** [comment]
I'd be happy to take a try at changing this, if its something you'd be interested in merging.

**Comment by kazu-yamamoto** [comment]
Yes. Please go ahead!
