### ISSUE TITLE
Fails to build on GHC 7.6.3

### ISSUE THREAD

**Issue by ndmitchell** [yesodweb/wai#340]
I see:

    Preprocessing library warp-3.0.9.1...
    Network/Wai/Handler/Warp/IO.hs:18:8:
        Could not find module `Data.ByteString.Builder.Extra'
        It is a member of the hidden package `bytestring-builder-0.10.4.1.1'.
        Perhaps you need to add `bytestring-builder' to the build-depends in your .cabal file.
        Use -v to see a list of the files searched for.

Full log here: https://travis-ci.org/ndmitchell/bake/jobs/51803993

**Comment by snoyberg** [comment]
Pinging @manny-fp

**Comment by manny-fp** [comment]
We could just add bytestring-builder to the build-depends, since it will do nothing when bytestring is new enough.  However, I ran into a problem when bytestring 0.10.2.* is installed along with bytestring-builder, since they both have `Data.ByteString.Builder.Extra` modules (Just checked, and I think this problem was introduced in https://github.com/lpsmith/bytestring-builder/commit/cc5b229cb3539982fd7e217e1d570c044cdbc0f5, because I remember testing for this case in the past).  So that means using flags to depend on bytestring-builder if bytestring <0.10.2.

**Comment by manny-fp** [comment]
(just filed an issue for with bytestring-builder: https://github.com/lpsmith/bytestring-builder/issues/6)

**Comment by snoyberg** [comment]
I've just released @manny-fp's patch to Hackage. @ndmitchell can you check if that solves things?

**Comment by ndmitchell** [comment]
@snoyberg that fixed it on 7.6.3 for me.

**Comment by snoyberg** [comment]
Cool, thanks guys!
