### ISSUE TITLE
Set END_STREAM on the last non-empty DATA frame when there will be no trailers.

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#459]
Firefox sends RST_STREAM with CANCEL when Warp sends HEADERS + DATA.

This is probably because Warp sends 0-length DATA frame with END_STREAM set when trailers are empty. In the spec, 0-length DATA is legal. But this is redundant and this is the major case.

@awpr Is it possible to not generate 0-length DATA when trailers are empty?

**Comment by awpr** [comment]
I believe the spec explicitly condones this behavior.  Initially I had it
send an empty trailers block for this case, but Chrome considered that a
protocol error, so I changed it to use an empty data frame.

**Comment by kazu-yamamoto** [comment]
It appeared that 0 length data frames are sent twice. One with ACK and the other without ACK. It seems to me that these logically unnecessary frames give big impact on performance.

**Comment by awpr** [comment]
Interesting, it definitely shouldn't be sending two.  By ACK do you mean END_STREAM, and in the order you mentioned them?  e.g. is it sending DATA(flags=END_STREAM, "") followed by DATA(flags=0, "")?  If so that looks like a protocol error.

I'll try to find how it could end up doing this.

**Comment by kazu-yamamoto** [comment]
Sorry.
s/ACK/END_STREAM/

**Comment by kazu-yamamoto** [comment]
The following sequence occupies CPUs:

```
1150  sendto(13, "\0\0\0\0\0\0\0\0\3", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\3", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\0\0\0\0\5", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\5", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\0\0\0\0\7", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\7", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\0\0\0\0\t", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\t", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\0\0\0\0\v", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\v", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\0\0\0\0\r", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\r", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\0\0\0\0\17", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\17", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\0\0\0\0\21", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\21", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\0\0\0\0\23", 9, 0, NULL, 0) = 9
1150  sendto(13, "\0\0\0\0\1\0\0\0\23", 9, 0, NULL, 0) = 9
```

**Comment by awpr** [comment]
That's weird, but at least it's not a protocol error since the END_STREAM is always the last one.

There are only 2 places that put DATA headers into the buffer: sendTrailers, and fillDataHeaderSend.  The former always sets END_STREAM, so the unexplained frames must be coming from calls to fillDataHeaderSend.

There are only two calls to that, and one is guarded by a check for nonzero length.  So, barring buffer misuse bugs, the non-END_STREAM ones must be coming from https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/HTTP2/Sender.hs#L132.

It looks like this can happen when the sender starts working on a stream, doesn't find any bytes to send, and doesn't find any further items on the queue.  I thought that wasn't allowed to happen -- don't we only enqueue a stream when it has output available?

We should be able to patch the symptom by adding a similar check for nonzero length at the other fillDataHeaderSend call, but I'm suspicious that streams are getting enqueued when they shouldn't be.

**Comment by kazu-yamamoto** [comment]
@awpr Please review the patch above.

**Comment by kazu-yamamoto** [comment]
I'm closing this because we have started over HTTP/2 code.
