### ISSUE TITLE
warp-tls: Status code 200 for insecure request denial

### ISSUE THREAD

**Issue by michael-swan** [yesodweb/wai#462]
It's really a minor detail, but perhaps a different status code such as 403 would be more fitting for a request denial due to an insecure request being made.

See https://github.com/yesodweb/wai/blob/master/warp-tls/Network/Wai/Handler/WarpTLS.hs#L465

**Comment by reiddraper** [comment]
I believe the correct status code is HTTP 426. See [RFC 2817](http://tools.ietf.org/html/rfc2817#section-4.2).

**Comment by snoyberg** [comment]
Sounds like a good change to me, can you send a PR?

**Comment by kazu-yamamoto** [comment]
:+1:

**Comment by kazu-yamamoto** [comment]
The current code hard-codes "HTTP/1.1" and "TLS/1.0". What if "HTTP/2" and "TLS/1.1" or later?

I discussed this issue with my friends. I seems to us that RFC 2817 recommends 426 status code to redirect from 80 port to 443 port. But in this case, WarpTLS is listening to 443 port.

I would suggest another error status code for HTTP/1.1 to avoid this hard coding. I believe that `Content-Length:` is also necessary.

If we wish to distinguish HTTP/1.1 and HTTP/2 based on the HTTP/2 prefix, `GOAWAY +  INADEQUATE_SECURITY` would be suitable for HTTP/2. But I don't know it's worth implementing since this is a rare error case.
