### ISSUE TITLE
Switch to strict ByteString from Builder in StreamingBody

### ISSUE THREAD

**Issue by nikita-volkov** [yesodweb/wai#528]
I see no reason to force the users to resort to a builder for this and more so to a specific one. Picking a specific implementation from an area with a high competition goes against WAI's generality. That is besides ["blaze-builder" actually being the least efficient amongst the competition](https://github.com/nikita-volkov/bytestring-builders-benchmark).

I suggest to switch to the following definition:

```haskell
type StreamingBody = (Data.ByteString.ByteString -> IO ()) -> IO () -> IO ()
```

**Comment by nikita-volkov** [comment]
Actually, it would be best to get rid of it in all other parts of the API too (e.g., `ResponseBuilder` could be `ResponseLBS`).

**Comment by snoyberg** [comment]
There are reasons given in the documentation itself justifying why a Builder is chosen instead of just a raw ByteString, and this issue does not address any of them.

http://haddock.stackage.org/lts-5.11/wai-3.2.0.1/Network-Wai.html#v:responseBuilder

**Comment by nikita-volkov** [comment]
Thanks for the prompt response, Michael. Although I wouldn't expect it to be any other way with you :)

Those arguments seem to apply only to ResponseBuilder, and although I strongly suspect we can find a better solution for that, it will require benchmarking, which will be a time-consuming endeavour, so I'll pass on that for this time.

However I don't see these arguments making sense in case of StreamingBody. The point of it is to directly send chunks of data thru IO. What does Builder have to do with that?

**Comment by snoyberg** [comment]
The exact same arguments applying to a StreamingBody, at least for the initial chunks (up until the first flush).

**Comment by kazu-yamamoto** [comment]
Just FYI.

Recently, blaze-builder's `Builder` is equal to bytestring's `Builder`. The bytestring-builder package does this magic.

If we use `Builder`, it can support strict, lazy and short ByteStrings. It seems to me that there is no reason to limit supported data structures only to strict ByteString.

**Comment by nikita-volkov** [comment]
> It seems to me that there is no reason to limit supported data structures only to strict ByteString.

In the end it is the strict bytestrings that get sent over the network. So it is wrapping them in builders that is limiting. In this case it is even more limiting, since both "blaze-builder" and Builder of "bytestring" are up to 4 times slower than competition.

**Comment by kazu-yamamoto** [comment]
I guess that the best way is to input your knowledge to bytestring's `Builder` to improve its performance. This does not effect any clients of WAI.

@nikita-volkov What do you think?

**Comment by nikita-volkov** [comment]
@kazu-yamamoto

So you suggest I rewrite "bytestring" so that you won't have to change a signature in "wai"? Is this a serious argument?

You've skipped this point, BTW:

> In the end it is the strict bytestrings that get sent over the network. So it is wrapping them in builders that is limiting.

**Comment by snoyberg** [comment]
@nikita-volkov If I may suggest: Kazu is answering your points very politely, and your response to him sounds antagonistic. If I can elaborate on what I _think_ Kazu is saying:

The Builder datatype in bytestring is central to the Haskell ecosystem at this point, has features not covered by your example alternative (such as the ability to fill a buffer from a short ByteString), and has been tested in a wide variety of real-world applications for both correctness and performance. While you have shown on one micro-benchmark that there are faster alternatives, this doesn't necessarily demonstrate that, in the wide variety of use cases we are targeting, those alternatives will always be faster.

If there really are potential optimizations to bytestring's Builder implementation, it would be more advantageous for everyone involved if you would be able to get those changes included upstream. Is there an inherent reason why such an approach couldn't work?

Note that this isn' so we "won't have to change a signature in wai," it's so that all users benefit from this, we have a consistent library ecosystem, and we don't need to change horses again two months from now when someone else discovers a micro-optimization and puts it in a new library instead of improving an existing library.

Apologies to Kazu if I misinterpreted your comments :)

**Comment by kazu-yamamoto** [comment]
@snoyberg Thank you for your explanation. You explained what I want to say. Since English is not my native language, my words are sometime too short. Sorry.

@nikita-volkov As you may know, I love high performance. And I respect your benchmark. Adding a new constructor to `Response` such as `ResponseStreamByteString` is easier. But if you want to change the signature of `ResponseStream`, it breaks backward compatibility. We need to study how this change will effect existing WAI applications and compare the trade-off between performance improvement and compatibility impact. Probably, many users would be against this change.

On the other hand, if you can bring your experience and knowlege to bytestring's `Builder`, we can maintain backward compatibility and even other projects than WAI apps enjoy the performance improvement. This story is very appealing to me.

**Comment by nikita-volkov** [comment]
I had no intention to sound rude or anything. Sorry if I did. I often forget that written words are easier to misinterpret.

@snoyberg

I feel I need to make it clear that I'm not pushing "bytestring-tree-builder" on you to use in "wai". I'm only making a case for using strict bytestrings instead of any builder there. I.e., for leaving the choice of how to deal with bytestring chunks to the end-user.

> features not covered by your example alternative (such as the ability to fill a buffer from a short ByteString)

Let's be honest. Is this really an important feature? Have you ever used `ShortByteString` for that? In my practice I haven't met a single case where I would benefit from using that type at all, forget about lifting it to `Builder`.

Either way, I don't see why that feature couldn't be implemented in "bytestring-tree-builder" if required.

> While you have shown on one micro-benchmark that there are faster alternatives, this doesn't necessarily demonstrate that, in the wide variety of use cases we are targeting, those alternatives will always be faster.

At very least the benchmark proves that the standard builder is anything but an optimal choice. Which adds to my point of pushing it on the users of "wai" being a questionable decision.

BTW, even in your added benchmarks, the standard builders are still notably outperformed by "buffer-builder".

> If there really are potential optimizations to bytestring's Builder implementation, it would be more advantageous for everyone involved if you would be able to get those changes included upstream. Is there an inherent reason why such an approach couldn't work?

It is not the optimizations that makes the difference here, but altogether different approaches to the problem.

Apart from that, making even minor changes to centric packages has shown to be a quite bureaucratic procedure filled with endless debates in my experience. Not a fan of spending time on any of that. Would rather author my own package and retain a freedom to explore the design-space.

> Note that this isn' so we "won't have to change a signature in wai," it's so that all users benefit from this, we have a consistent library ecosystem, and we don't need to change horses again two months from now when someone else discovers a micro-optimization and puts it in a new library instead of improving an existing library.

Which is why a general API needs to be as unopinionated as possible. Picking a specific builder amongst a plethora of alternatives is an opinionated decision. Picking `ByteString`, which virtually has zero competition, is not.

@kazu-yamamoto

> We need to study how this change will effect existing WAI applications and compare the trade-off between performance improvement and compatibility impact.

It's not just about the performance, I'm trying to point out an issue of the API. I believe that the only purpose of "wai" is to be a language of communication for an ecosystem of packages. With that said I believe that it is wrong for it to make opinionated choices in ambiguous situations, and especially when there is an ovious unopinionated alternative.

> On the other hand, if you can bring your experience and knowlege to bytestring's Builder, we can maintain backward compatibility and even other projects than WAI apps enjoy the performance improvement. This story is very appealing to me.

It is not the optimizations that makes the difference here, but altogether different approaches to the problem.

Apart from that, making even minor changes to centric packages has shown to be a quite bureaucratic procedure filled with endless debates in my experience. Not a fan of spending time on any of that. Would rather author my own package and retain a freedom to explore the design-space.

**Comment by snoyberg** [comment]
I'm definitely getting the feeling in this discussion that the points Kazu and I are making are being blatantly ignored. For example, I already commented that moving to `ByteString` would be a pessimization for a common case: wanting the beginning of a stream to be composed together with the headers. AFAICT, you've ignored that point completely. I'm going to give a little more feedback on your comments here as well.

> Apart from that, making even minor changes to centric packages has shown to be a quite bureaucratic procedure filled with endless debates in my experience. Not a fan of spending time on any of that. Would rather author my own package and retain a freedom to explore the design-space.

There's a reason for the bureaucracy in this case: a core library needs to make certain it's optimizing for good overall performance, not targeting one specific benchmark. I've played around with builder work in the past as well, and while it's really easy to make an implementation that outperforms bytestring-builder on a simplistic benchmark, this misses out on a lot of real-world examples.

You're essentially asking us in wai to bypass a community process designed to come to the most efficient outcome, because you're not willing to be part of that process. Then throwing it in Kazu's face and implying it's because he doesn't feel like changing the API is pretty disingenuous.

> Which is why a general API needs to be as unopinionated as possible. Picking a specific builder amongst a plethora of alternatives is an opinionated decision. Picking ByteString, which virtually has zero competition, is not.

This isn't at all a true statement. Choosing a `ByteString`-only API is _very_ limiting. Some examples:

* Yielding one single `ByteString` at a time avoids the possibility of vectorized I/O for sending multiple chunks at once. A builder approach allows that
* `ByteString`s are not as efficient as storable `Vector Word8`s, since the latter only hold a `ForeignPtr` and a single `Int` instead of two `Int`s.
* For that matter, requiring immutable buffers be sent to us instead of allowing for mutable buffers is a potentially significant allocation overhead (which, again, can be bypassed by using builders)

Beyond all of this, there are major add-on complication impacts from switching away from a Builder, which allows for easy composition. All middlewares would need to be rewritten, and it's not clear how optimally they _could_ be rewritten.

> So it is wrapping them in builders that is limiting. In this case it is even more limiting, since both "blaze-builder" and Builder of "bytestring" are up to 4 times slower than competition.

blaze-builder has always provided an `insertByteString` call, which yields a single `ByteString` immediately. My understanding (from having read the code) is that there should be almost no overhead from using that vs switching the entire API to use strict `ByteString`s directly. If you believe this is mistaken, some benchmarks showing otherwise would be interesting.

* * *

What I'm trying to get across here is:

* There are many design points involved in choosing this API
* You've already ignored at least one point I've made
* Trying to claim we have to be "unopinionated" as the only guiding principle doesn't work, since every choice will be opinionated.

**Comment by awpr** [comment]
One more minor point here: the concern of concatenating stream data with other data before sending it is much stronger for HTTP/2, where every chunk of data is appended to some preceding buffer contents -- for chunks that form the start of a frame, they're appended to the 9-byte frame header, and for subsequent chunks, they're appended to the earlier data in the frame.  Using ByteString, or indeed any type that comes with its own memory, is going to require an extra copy for every chunk, or an extra syscall per chunk if everything is rewritten to send the given buffers directly to the socket (which is likely to be much slower).  The difference matters when a chunk would be the concatenation of lots of small text fragments (like HTML) or generated from some other data structure (like JSON and other serialization).

If I understand correctly this is basically the same reason that nghttp2 uses "buffer-filling callbacks" (i.e. what builder-style APIs look like when I/O is unrestricted) as the application-level API for implementing streams.

I'm not going to claim that the Builder in 'bytestring' is the best choice, since I haven't done all the benchmarking myself, but ByteString is not a suitable alternative.

**Comment by kazu-yamamoto** [comment]
> Let's be honest. Is this really an important feature? Have you ever used ShortByteString for that?

Just FYI:

`ByteString`s are pinned objects. This means that if we use `ByteString` heavily for a long time, memory got fragmented. (If we use `take` for 4KiB `ByteString` and hold the new short substring, the original one is never GCed.) To avoid this, some users are using `ShortByteString`s. I know there are at least two productions (which are not open source) using `ShortByteString`.

**Comment by winterland1989** [comment]
An interesting thing is that: there's no chunked encoding implementation other than `chunkedTransferEncoding :: Builder -> Builder` from blaze-builder. If we switched to `ByteString` based interface, wouldn't  this `ByteString` be a intermedia data structure from chunked encoder's view?@nikita-volkov, I think this cover two issue here:

+ You can improve `Builder`'s performance by using length accumulator to optimise allocation, this is done in variety situations, for example, you can check fast-logger's `LogStr` type. I don't quite get why a binary-tree based solution will be better than linked-list based, since you are not doing parallel copy.

+ It's not possible to do something like chunked encoding with these length accumulator approach in general, because encoding may change chunk size. If you'd like to use `TreeBuilder` to implement a chunked encoding encoder, please go ahead. i don't think do it without traverse all the leaf and encode them all is possible.

So my point is, the `Builder` type is not designed to be the optimal one in `concat` sense, it's design to be the optimal one in variety processing situations where a lazy `ByteString` are too expensive to construct.

Once you want to do `Builder` transforming, you will be amazed how easy that `ByteString.Builder` interface provide. But i do think there should be a better solution to answer the `concat` problem.

**Comment by kazu-yamamoto** [comment]
I would close this issue. Please reopen if necessary.
