### ISSUE TITLE
Expected behaviour when catching TimeoutThread?

### ISSUE THREAD

**Issue by agrafix** [yesodweb/wai#602]
In an application I am currently debugging a response handler catches all exceptions via 

```haskell
`catch` \(e :: SomeException) ->
```

and then logs the expection and continues to do it's work. While I know that this is bad coding and should be fixed right there, I was wondering what the expected behaviour of warp for this kind of situation would be?

**Comment by snoyberg** [comment]
Correct me if you think otherwise @kazu-yamamoto, but I think we do not currently handle this case well in Warp. With this code, I believe today you would end up blocking the slowloris protection and the connection would remain open. I think we need the following improvements in Warp:

* Whenever we send a `TimeoutThread` exception, also immediately kill the open connection, so that even if the application catches the exception, the attack is stopped.
* Modify the `Exception` instance for `TimeoutThread` so that it inherits from `AsyncException`, so packages like `safe-exceptions` work correctly.

**Comment by kazu-yamamoto** [comment]
+1

**Comment by agrafix** [comment]
Sounds good! I hope to find time for a PR soon :-)
