### ISSUE TITLE
Distinguishing exceptions caught in accept loop vs. in handlers?

### ISSUE THREAD

**Issue by osa1** [yesodweb/wai#648]
I'm trying to debug a warp server that somehow get stuck and stop accepting new connections (but existing websocket handlers keep running). I'll now add logging with `setOnException` but looking at the warp source code it seems like there's no way to distinguish errors caught in handlers (in `Run.hs:fork`) and in the accept loop (`Run.hs:acceptNewConnection`). Because I'm only interested in the latter this makes debugging harder.

I'm wondering if I'm right that I can't distinguish these two. If yes then could we maybe wrap these exceptions passed to `setOnException` in these two places with different constructors? (e.g. with something like `data WarpError = AcceptError SomeException | HandlerError SomeException`) Can you think of any other ways of distinguishing these two?

**Comment by snoyberg** [comment]
Are you asking how to modify the source code on a custom fork of the repo to perform debugging, or to make a change to the official repo?

**Comment by osa1** [comment]
Sorry for the late response,

I managed to make some progress with the current exception handler callbacks of warp. One of the things that I still need to do but I can't (without modifying warp) is to log remote host address on every `accept()`. For this I currently need to modify `warp` and `warp-tls`, to add something like:

```
    peer_name <- getPeerName s
    putStrLn ("accepted socket: " ++ showSockAddr peer_name)
```

where `s` is the accepted socket. (`showSockAddr` is a custom function because `network`s `SockAddr` type doesn't have a `Show` instance)

Not sure if adding this capability of logging accepted remote hosts makes sense but if it does let me know and I can send a PR.

**Comment by snoyberg** [comment]
If this would be an extra setting available, I don't see a problem.

**Comment by kazu-yamamoto** [comment]
But we should make consensus about a new setting name.

**Comment by gzh** [comment]
My apologies @osa1, may I ask whether have you found out what was the reason for initial problem? ("a warp server .. get stuck and stop accepting new connections (but existing websocket handlers keep running")?

Seems like I ran into similar behavior of Warp in my project (occasionally something happens, so that HTTP server keeps serving on existing connections, but does not accept any new connections, the listening socket is left open in the system, and the new connections attempts are stalled in the backlog which is shown by netstat), under relatively high load. I'm going start the research on what might be the cause for this, certainly starting from my own code, but it would be great to get a hint if you've solved this issue in your case.

**Comment by osa1** [comment]
@gzh in our case it turns out another library was leaking file descriptors so the process was running out of file descriptors and `accept()` was returning an error. You can `strace` your process to see if `accept()` is failing, and if so, it may be that you're also running out of file descriptors (maybe because some other code is leaky).

**Comment by gzh** [comment]
@osa1 Thank you for the prompt reply! 
File descriptor leak is probably not my case, because I'm watching for number of FDs via /proc - it's OK, and I also see other threads keep on successfully creating and opening other sockets in that process after Warp has failed. In fact there's even another instance of Warp on another port in the same process, and that other instance of Warp keeps working normally, serving the new connecting clients, after the first Warp gets stuck. Anyway, thank you, I'll be doing further research on this.
