### ISSUE TITLE
Feature request: Setting to disable Last-Modified for ResponseFile

### ISSUE THREAD

**Issue by chris-martin** [yesodweb/wai#680]
I'm serving files from a directory in which the files don't have timestamps (they're in `/nix/store`), and so Warp's automatic addition of the `Last-Modified` header is wreaking havoc with the browser's caching. Could there be something in `Settings` to disable this feature?

**Comment by Profpatsch** [comment]
I have tried doing this with the current wai-app-static:

```
  where
    -- | Remove all caching information from a File returned by our static fileserver.
    -- This is important if we really want to turn of caching.
    uncacheFile :: StaticTypes.File -> StaticTypes.File
    uncacheFile f =
      let
        fileGetHash = case cachingMode of
          -- Every file gets the same ETag; they are distinguished by their URL
          -- and we assume the files are all updated at the same time.
          -- (for example when a new nix store path is used, which can serve as ETag)
          WithStaticETag (ETag tag) -> pure $ Just tag
          -- If caching is completely disabled, we also don’t have an ETag to return
          NoCaching -> pure Nothing
        -- Remove modification time
        fileGetModified = Nothing
      in f { fileGetHash, fileGetModified
           , fileToResponse = \s h -> let res = ((f & fileToResponse) s h) in Debug.Trace.traceShow (Network.Wai.responseHeaders res) res
           }

    -- | uncacheFile if it’s a file
    uncacheLookupResult :: StaticTypes.LookupResult -> StaticTypes.LookupResult
    uncacheLookupResult = \case
      LRFile f -> LRFile $ uncacheFile f
      LRFolder f -> LRFolder f
      LRNotFound -> LRNotFound

    -- | Base on default file server settings but disable file modifications caching.
    settings =
      let
        base =
          StaticFiles.webAppSettingsWithLookup
            rootPath
            -- disable file hashing, the tag is set in 'uncacheFile' if applicable
            (\path -> Debug.Trace.trace path $ pure Nothing)
      in base {
        -- remove modification time caching and add etags if applicable
        ssLookupFile = \pcs -> uncacheLookupResult <$> (base & ssLookupFile) pcs,
        -- no index.html redirect
        ssIndices = [],
        ssRedirectToIndex = False,
        -- no directory listing of files
        ssListing = Nothing,
        -- disable `cache-control` HTTP header
        ssMaxAge = NoMaxAge,
        -- if ETag caching is enabled, of course we want to use it.
        ssUseHash = case cachingMode of
          WithStaticETag _ -> True
          NoCaching -> False
      }
```

I patch `ssLookupFile` to remove the file modification time from the result, which makes it fall to the `Nothing` case here:

https://github.com/yesodweb/wai/blob/73f79222b52c02f006becad83c44caf30736b640/wai-app-static/Network/Wai/Application/Static.hs#L189-L193

However, the `Last-Modified` header is still set by warp, in `conditionalRequest`:

https://github.com/yesodweb/wai/blob/73f79222b52c02f006becad83c44caf30736b640/warp/Network/Wai/Handler/Warp/File.hs#L41-L42

This is because “simple” `RspFile` invocations always set it:

https://github.com/yesodweb/wai/blob/73f79222b52c02f006becad83c44caf30736b640/warp/Network/Wai/Handler/Warp/Response.hs#L272-L284

wai-app-static passes `responseFile` with `Nothing` somewhere, which is turned into `RspFile`. If it were to pass a `Just FilePart` instead, the header wouldn’t be added.

There’s two ways to solve this:

1. Make `wai-app-static` use `Just FilePart` instead of `Nothing`. (less intrusive)
2. Add an option to `warp`’s `RspFile` to not set the `Last-Modified` header. I don’t think this can be done without changing `Wai`’s interface (breaking change, not a good idea) or making warp *not* set `Last-Modified` by default.

@kazu-yamamoto would you be okay with removing implicitely setting the `Last-Modified` header in warp? If not, we should use `FilePart`.

**Comment by kazu-yamamoto** [comment]
Does #791 also fix this?

**Comment by Profpatsch** [comment]
@kazu-yamamoto I don’t think so, it will always add a `Last-Modified` header when passing `Nothing` instead of `Just Filepart` to `respondFile`, right? afaik `wai-app-static` uses `respondFile` with `Nothing`, so it should still create a `Last-Modified` header in any case.

**Comment by Profpatsch** [comment]
Yeah, it calls `responseFile`:

https://github.com/yesodweb/wai/blob/9a89f81c9a77f40ce60c87770b6513e920077314/wai-app-static/WaiAppStatic/Storage/Filesystem.hs#L98

Of course you can overwrite it, but then you have to re-implement `fileSystemLookup`, which is not exposed.

**Comment by kazu-yamamoto** [comment]
It seems to me:

- In the case of `Just`, `addContentHeadersForFilePart` is called. It does not add `Last-Modified:`.
- In the case of `Nothing`, `conditionalRequest` is called. It does not add `Last-Modified:` if exists.

Am I missing something?

**Comment by Profpatsch** [comment]
> Am I missing something?

My use-case (and I’m assuming @chris-martin’s as well) is serving static files with `wai-app-static` (which is also in this repository).

`wai-app-static` passes `Nothing` to `responseFile`, which means that a `Last-Modified` header is always added. We would like a way to disable adding `Last-Modified` headers alltogether when using `wai-app-static`.

I realize you are mainly the author of `warp`, so you might not have a specific interest in `wai-app-static`.

So I think the best solution here is to add a configuration option to `wai-app-static` and if no `Last-Modified` header should be added make it use `Just FilePart` so that warp calls `addContentHeaderForFilePart` and consecutively doesn’t add a file header.

**Comment by kazu-yamamoto** [comment]
Ah. You were talking about `wai-app-static` while I was talking about `warp`. Sorry but I cannot help you on this issue.

**Comment by snoyberg** [comment]
Closing as invalid, setting response headers like this is intentional.

**Comment by Profpatsch** [comment]
I will add that the use-case still exists and all things I noted above still apply.
