### ISSUE TITLE
Accessing warp's bound sockets

### ISSUE THREAD

**Issue by defanor** [yesodweb/wai#721]
Sometimes it is handy to output a "listening on" message after starting a server (e.g., as in https://github.com/myfreeweb/wai-cli/issues/3), but apparently with Warp it would require a custom `runSettings` function. It seems it may be more appropriate to pass a `Socket` and/or a `SockAddr` to a function set with `setBeforeMainLoop`.

**Comment by snoyberg** [comment]
You can accomplish this with runSettingsSocket

**Comment by kazu-yamamoto** [comment]
I have no motivation to change the current API.

**Comment by defanor** [comment]
Okay, then closing the issue.

**Comment by bitc** [comment]
I would like to voice my support for this feature.

warp `runSettings` function supports the use case of binding to port 0, which tells the operating system to bind to any free port. The problem is that it is then impossible to know which port we are listening on, making this feature useless.

As has been mentioned, we can use `runSettingsSocket` ourselves to get this functionality. The problem is that when you create your own Socket then you will want to set `CloseOnExec` flag on your socket, which is only in the `unix` package so now you lose windows compatibility, plus there is quite a bit of additional boilerplate code to create your own Socket.

warp already deals with all this complexity, so it is a shame to have to re-implement it yourself in your own project, just so you can know what port you are listening on.

Thank you
