### ISSUE TITLE
dejafu for AutoUpdate

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#888]
I'm trying to use dejafu to make sure no race condition in the current AutoUpdate. [A Concurrency Testing Library for Haskell](https://eprints.whiterose.ac.uk/118198/1/DejaFu.pdf) pointed out two races.

I have imported AutoUpdate from dejafu-test and modified to synchronize auto-update v0.1.1.4 that has the first bug as descrived in #294 and the paper. My work branch is here: https://github.com/kazu-yamamoto/wai/tree/dejafu

The autocheck found a race:

```
> autocheck deadlocks
[fail] Successful
    [deadlock] S0--------S1-----------S0-
[fail] Deterministic
    [deadlock] S0--------S1-----------S0-

    () S0--------S1--------p0--
False
```

Then I updated this file to synchronize v0.1.6:

```
> autocheck deadlocks
[pass] Successful
[pass] Deterministic
True
```

Nice!

However, I don't understand whether or not the second race has been fixed.

```
> dejafus [("Consistent Result", alwaysSame)] nondeterministic 
[fail] Consistent Result
    0 S0-----------S1------p0----

    1 S0-----------S1------p0-P1---S0---S1-----p0--
False
```

@barrucadu I cannot find `dejafus'` so I'm not sure that I did a right test. Would you tell us whether or not the second race still exist?

**Comment by kazu-yamamoto** [comment]
@barrucadu I hope you find this issue.

**Comment by barrucadu** [comment]
Ok, well, I don't really remember exactly what I was showing in the paper there (and I seem to have left that part of the example out of my thesis - but kept the deadlock part), but returning either `0` or `1` here is expected because this code is inherently racy: if you read the value at the same time it's supposed to be updated, what happens?  Well, if you're slightly earlier you'll get the old value, if you're slightly after you'll get the new value.  Maybe I was just wrong back then and nobody spotted it?  Who knows.

The deadlock doesn't happen, which is the important thing.

**Comment by kazu-yamamoto** [comment]
@barrucadu Thanks. I'm relieved to hear that. Let's close this issue.
